name: build

on:
  push:
    branches:
      - main
      - dev*
  pull_request:

jobs:
  build_int32:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '3.2', '3.3', '3.4' ]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build and test with Rake
        run: bundle exec rake
  build_int64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '3.2', '3.3', '3.4' ]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build and test with Rake
        run: bundle exec rake compile -- --with-use-int64 && bundle exec rspec
  build_blas:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '3.2', '3.3', '3.4' ]
    steps:
      - uses: actions/checkout@v5
      - name: Install BLAS
        run: sudo apt-get install -y libopenblas-dev
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build and test with Rake
        run: bundle exec rake compile -- --with-blas-dir=/usr/lib/x86_64-linux-gnu/openblas-pthread --with-blas-lib=openblas && bundle exec rspec
